### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/Timepicker#1]
Update the readme.md

**Comment by patricksavalle** [comment]
@RoelandSalij  @Ivanmoorsel I noticed the Mobbr logging on this URL. Let me clarify why Mobbr cannot divide the pledges. 

First of all, the error message is unclear, we will try to get that better. But issues without any commits, can currently not be rewarded, since they don't show up in the GIT statistics. And it looks like the README of Github is a special (undocumented) case on this. Also looking into this.

**Comment by patricksavalle** [comment]
@RoelandSalij @Ivanmoorsel It is fixed. The event stream of Github turned out to be less regular than expected :) It should work as expected now.

**Comment by RoelandSalij** [comment]
Nice, we'll give it another try!
